### ISSUE TITLE
Clarifying assets licensing

### ISSUE THREAD

**Issue by akien-mga** [w84death/Tanks-of-Freedom#24]
Hi there :-)

I'm looking at packaging ToF for my Linux distro (Mageia) now that I have a package for Godot 2.0.

I'd like to see the assets licensing clarified before I can push it to the main Mageia repos as fully libre. For example the font in use is under the OFL, so it should be mentioned somewhere.
The link to Grand Beats' music and sfx in the README.md brings to a commercial platform to buy sfx (which does not imply that the ones you use aren't under a DFSG-free license, but it does not make it clear either ;-)).

Mentioning the licenses next to the authors in the README.md would already be a nice way to make it all clearer I guess.

Thanks in advance, and thanks for this awesome libre game! Godot rules ;-)

**Comment by czlowiekimadlo** [comment]
Hey!

Thanks for helping us spread the Godot and ToF love ;)

I have added OFL mention in the README.md file. As for the music, we are cooperating directly with the authors, but we never really discussed licensing. 

I'm not sure if current version of the game even contains any music from Mathias. 

Grand Beats is creating music for our other games, so these should be freely licensed without issues, but for ToF he borrowed us some tracks from his commercial album, so I'll discuss this with him and update the README file accordingly.

**Comment by czlowiekimadlo** [comment]
I have talked with QmYaan (Grand Beats), and he agreed to provide these assets for us under CC BY-SA 4.0 license, which is DFSG-compatible. 

License mentions are now on the creators list, and in the licenses part of the Readme, as well as in license file.

I have omitted license for old files from Mathias, I know, that these can be pulled from git history, but even if we consider these non-free, It should not be an issue, as current version of the game does not use these files.

Please let me know if there is anything else about licensing, that needs clarification. Otherwise I will close this ticket :)

**Comment by akien-mga** [comment]
It looks great, thanks! The only thing left would be to specify the gfx's license too, I assume they are under the MIT like the code as they were also done by @w84death, but it's clearer if it's written somewhere, as usually MIT will be considered as referring only to the code files.

**Comment by czlowiekimadlo** [comment]
As far as I can tell, the only license @w84death needs is "Do what you want, just don't bother me" :D I will add appropriate info later, but it will be MIT.

**Comment by czlowiekimadlo** [comment]
Explicit mention about MIT license added to the graphics section.

**Comment by akien-mga** [comment]
Thanks, it's all good as far as I'm concerned! :)
