### ISSUE TITLE
Icon size may be too big

### ISSUE THREAD

**Issue by moshpirit** [w84death/Tanks-of-Freedom#25]
The ToF's [icon](https://github.com/w84death/Tanks-of-Freedom/blob/master/icon.png) is really big and needs a bit to get loaded on my launcher ([KISS launcher](https://f-droid.org/repository/browse/?fdfilter=kiss&fdid=fr.neamar.kiss)). I [reported the issue](https://github.com/Neamar/KISS/issues/402#issuecomment-190092042) and looks like it's not a launcher issue, but this icon. So I've thought that no one's going to use a 1.024px × 1.024px icon on his device. So maybe it could use a [thumb](https://anonmgur.com/up/2ebe004aea12d80f41e741297ec666dd.png) for this and keep this icon as _full-sized-icon.png_ if you'd like to keep it for artwork (I personally would keep both: thumb and full sized logo).

I don't know if this is actually the icon used but that's my understanding. I'm sorry if I'm reporting this silly issue, I don't want to bother you at all.

Thanks for all your work! :)

**Comment by czlowiekimadlo** [comment]
@w84death have provided more icons, you can find them in the assets/icons/ folder. Default engine settings for icons are also pointing now to a smaller version. If you still have some issues, or need a different icon size, you will have to modify engine.cfg for your export.

Fixed in 7cfefbc2e360eace41cd101501267fb72ce0a408

**Comment by moshpirit** [comment]
Thank you! :)
