### ISSUE TITLE
32-bit binaries?

### ISSUE THREAD

**Issue by andoruB** [w84death/Tanks-of-Freedom#4]
Will you guys ever provide 32bit binaries for Linux (and maybe other platforms)? If not how could make a stand-alone build in Godot? I'm currently only able to load the game files within it.

**Comment by czlowiekimadlo** [comment]
We did not plan on providing 32bit binaries of the game. Only exception is for Windows, because 64bit is crashing for unknown reason.

If you wish to build the game as standalone, please download Export Templates from Godot website, add them to your Godot editor (click Settings button in upper-right corner when the project is opened, then select install option). Then you should be able to use Export option in the upper-left.

You can find templates here: http://www.godotengine.org/wp/download/

**Comment by andoruB** [comment]
Are you interested in distributing my own 32bit binary then?

**Comment by czlowiekimadlo** [comment]
Thank you for the offer, but currently we are not going to put 32bit binaries up. Managing many different versions on itch.io is a bit of a chore, so we are sticking to only one build per platform. I think we may add information, that 32bit ones are available on-demand though.

**Comment by andoruB** [comment]
Alright, understood. Thanks for the answers.
