### ISSUE TITLE
Attach official binaries to releases on Github

### ISSUE THREAD

**Issue by farooqkz** [w84death/Tanks-of-Freedom#80]
Because:
 1- Github gives a direct link and does not require JavaScript.
 2- Two links on different servers is better than one.
 3- Github is easier to access(at least for many users if not all of them).

**Comment by czlowiekimadlo** [comment]
Considering numbers of downloads for already existing channels and the github visits, it is easier for only a small fraction of users. Also many users interested in the sources prefer to explicitly use their own compiled engine instead of packaged game (e.g. most packagers for linux distros).

I think we will not add binaries for already released tags, but we are working on 0.7.0 release now, so we might add these new binaries here.

**Comment by farooqkz** [comment]
bump :)

These days we also have got Flathub

**Comment by farooqkz** [comment]
Closing as not revelant anymore

**Comment by czlowiekimadlo** [comment]
I have created PR for flathub to bump the version, but it looks like no one reviews those...

**Comment by farooqkz** [comment]
You mean someone from flathub team must review or the users?

**Comment by czlowiekimadlo** [comment]
I think it's someone from flathub. You can find them here https://github.com/flathub/in.p1x.TanksOfFreedom/pulls
