### ISSUE TITLE
Menu flickering

### ISSUE THREAD

**Issue by drummyfish** [w84death/Tanks-of-Freedom#87]
When you hold ESC key and move your mouse around, the menu flickers: [video](https://www.youtube.com/watch?v=aVSVLncRIm4&feature=youtu.be).

ToF Beta 0.6.3, Linux 64

**Comment by czlowiekimadlo** [comment]
Hi, thank you for the report. We are aware of this issue, though I'm afraid it can't be fixed right now, because it is caused by a weird input behaviour in the Godot Engine itself. Since Godot Engine is now focused on 3.x version, we do not expect them to do any further bugfixes in the 2.1.x branch anymore.
